name: Runner
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
  pull_request:
    branches: 
      - '**'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    
    - name: Nix Flake Check
      run: nix flake check
    - name: Run Checks
      run: |
        nix develop -c bash -c "
          cargo build --all-targets
          cargo test
          cargo fmt -- --check
          cargo clippy -- -D warnings
          cargo tarpaulin --ignore-tests
        "
    - name: Check Nix formatting
      run: nix develop -c bash -c "nixpkgs-fmt --check ."